ORANGE_SRC_DIR	:= $(LIBS_DIR)/orange

ORANGE_TARGET_DIR	:= $(TOP_DIR)/temp/libs/orange

ORANGE_TARGET_NAME	:= liborange.$(LIB_SO_SUBFIX)

orange: 
	$(MS_MAKEFILE_V)printf "$(COMPILE_P) $(ORANGE_TARGET_NAME) $(NOCOLOR)\n"
	-$(MS_MAKEFILE_V)mkdir -p $(ORANGE_TARGET_DIR)
	$(MS_MAKEFILE_V)$(MAKE) -C $(ORANGE_SRC_DIR) CC=$(TARGET_CC) TARGET_DIR=$(ORANGE_TARGET_DIR) TARGET_NAME=$(ORANGE_TARGET_NAME)
	-$(MS_MAKEFILE_V)mkdir -p $(PUBLIC_LIB_DIR)
	cp $(ORANGE_TARGET_DIR)/$(ORANGE_TARGET_NAME) $(PUBLIC_LIB_DIR)/$(ORANGE_TARGET_NAME)

orange-clean:
	$(MS_MAKEFILE_V)printf "$(CLEAN_P) $(ORANGE_TARGET_NAME) $(NOCOLOR)\n"
	$(MS_MAKEFILE_V)$(MAKE) -C $(ORANGE_SRC_DIR) clean TARGET_DIR=$(ORANGE_TARGET_DIR) TARGET_NAME=$(ORANGE_TARGET_NAME)
	-$(MS_MAKEFILE_V)rm -rf $(PUBLIC_LIB_DIR)/$(ORANGE_TARGET_NAME)
	$(MS_MAKEFILE_V)printf  "$(COMPILE_SUCCESS_P) $(ORANGE_TARGET_NAME) success $(NOCOLOR)\n"

LIBS   += orange
CLEANS += orange-clean


