#ifndef _H_MOD_FIRMWARE_
#define _H_MOD_FIRMWARE_

#define UPFW_UPDATE_TIMEOUT 60 * 60

#define SOFTWARE_ID_ALL 0
#define SOFTWARE_ID_WIPAP 1
#define SOFTWARE_ID_FRONTEND 2
#define SOFTWARE_ID_AC 3
#define SOFTWARE_ID_AC_NODE 4
#define SOFTWARE_ID_AC_ROOTER 5
#define SOFTWARE_ID_CCTV 6
#define SOFTWARE_ID_BACKEND 7
#define SOFTWARE_ID_PORTAL_CLIENT 8
#define SOFTWARE_ID_AC_PROC 9

#define FRONTEND_DIR "/home/wipap/frontend"
#define BACKEND_DIR "/home/wipap/backend"
#define WIPAP_DIR "/home/wipap"

#define MOUNT_UPDATE_SCRIPT "/home/root/mount_update.sh"

#define UPFW_QUERY_STATUS_IDLE 0
#define UPFW_QUERY_STATUS_RUNNING 1

#define UPFW_UPDATE_STATUS_IDLE 0
#define UPFW_UPDATE_STATUS_PREPARE 1
#define UPFW_UPDATE_STATUS_RUNNING 2
#define UPFW_UPDATE_STATUS_FINISHED 3

#define UPFW_UPDATE_STEP_NONE 0
#define UPFW_UPDATE_STEP_PREPARE 1
#define UPFW_UPDATE_STEP_DOWNLOADING 2
#define UPFW_UPDATE_STEP_UPDATING 3
#define UPFW_UPDATE_STEP_FINISHED 4

#define UPFW_AC_UPDATE_STATUS_PREPARE 1
#define UPFW_AC_UPDATE_STATUS_WORKING 2
#define UPFW_AC_UPDATE_STATUS_FINISHED 3

#endif
