INCLUDE         := -g -I${LIBS_DIR}
LDFLAGS         := -L/usr/lib -L/lib -L/usr/local/lib -L$(PUBLIC_LIB_DIR) -lorange
TARGET_TYPE:="$(LIB_SO_SUBFIX)"

SHELL := /bin/bash


include $(BUILD_COMMON_MK)


