WATCHDOG_SRC_DIR	:= $(LIBS_DIR)/watchdog

WATCHDOG_TARGET_DIR	:= $(TOP_DIR)/temp/libs/watchdog

WATCHDOG_TARGET_NAME	:= orange_watchdog.$(LIB_SO_SUBFIX)


watchdog: 
	cd ${WATCHDOG_SRC_DIR} && sh ./orange_watchdog_version.sh
	$(MS_MAKEFILE_V)printf "$(COMPILE_P) $(WATCHDOG_TARGET_NAME) $(NOCOLOR)\n"
	-$(MS_MAKEFILE_V)mkdir -p $(WATCHDOG_TARGET_DIR)
	$(MS_MAKEFILE_V)$(MAKE) -C $(WATCHDOG_SRC_DIR) CC=$(TARGET_CC) TARGET_DIR=$(WATCHDOG_TARGET_DIR) TARGET_NAME=$(WATCHDOG_TARGET_NAME)
	cp $(WATCHDOG_TARGET_DIR)/$(WATCHDOG_TARGET_NAME) $(PUBLIC_LIB_DIR)/$(WATCHDOG_TARGET_NAME)
	rm ${WATCHDOG_SRC_DIR}/orange_watchdog_version.c

watchdog-clean:
	$(MS_MAKEFILE_V)printf "$(CLEAN_P) $(WATCHDOG_TARGET_NAME) $(NOCOLOR)\n"
	$(MS_MAKEFILE_V)$(MAKE) -C $(WATCHDOG_SRC_DIR) clean TARGET_DIR=$(WATCHDOG_TARGET_DIR) TARGET_NAME=$(WATCHDOG_TARGET_NAME)
	-$(MS_MAKEFILE_V)rm -rf $(PUBLIC_LIB_DIR)/$(WATCHDOG_TARGET_NAME)
	$(MS_MAKEFILE_V)printf  "$(COMPILE_SUCCESS_P) $(WATCHDOG_TARGET_NAME) success $(NOCOLOR)\n"

LIBS   += watchdog
CLEANS += watchdog-clean


