THREAD_TASK_SRC_DIR	:= $(LIBS_DIR)/thread_task

THREAD_TASK_TARGET_DIR	:= $(TOP_DIR)/temp/libs/thread_task

THREAD_TASK_TARGET_NAME	:= orange_thread_task.$(LIB_SO_SUBFIX)

thread_task: 
	cd ${THREAD_TASK_SRC_DIR} && sh ./orange_thread_task_version.sh	
	$(MS_MAKEFILE_V)printf "$(COMPILE_P) $(THREAD_TASK_TARGET_NAME) $(NOCOLOR)\n"
	-$(MS_MAKEFILE_V)mkdir -p $(THREAD_TASK_TARGET_DIR)
	$(MS_MAKEFILE_V)$(MAKE) -C $(THREAD_TASK_SRC_DIR) CC=$(TARGET_CC) TARGET_DIR=$(THREAD_TASK_TARGET_DIR) TARGET_NAME=$(THREAD_TASK_TARGET_NAME)
	cp $(THREAD_TASK_TARGET_DIR)/$(THREAD_TASK_TARGET_NAME) $(PUBLIC_LIB_DIR)/$(THREAD_TASK_TARGET_NAME)
	rm ${THREAD_TASK_SRC_DIR}/orange_thread_task_version.c

thread_task-clean:
	$(MS_MAKEFILE_V)printf "$(CLEAN_P) $(THREAD_TASK_TARGET_NAME) $(NOCOLOR)\n"
	$(MS_MAKEFILE_V)$(MAKE) -C $(THREAD_TASK_SRC_DIR) clean TARGET_DIR=$(THREAD_TASK_TARGET_DIR) TARGET_NAME=$(THREAD_TASK_TARGET_NAME)
	-$(MS_MAKEFILE_V)rm -rf $(PUBLIC_LIB_DIR)/$(THREAD_TASK_TARGET_NAME)
	-$(MS_MAKEFILE_V)rm $(THREAD_TASK_SRC_DIR)/orange_thread_task_version.c
	$(MS_MAKEFILE_V)printf  "$(COMPILE_SUCCESS_P) $(THREAD_TASK_TARGET_NAME) success $(NOCOLOR)\n"

LIBS   += thread_task
CLEANS += thread_task-clean


