APP_WATCHDOG_SRC_DIR    := $(APPS_DIR)/test/
APP_WATCHDOG_TARGET_DIR := $(TOP_DIR)/temp/app/test
APP_WATCHDOG_TARGET_NAME:= test

test:
	mkdir  -p $(APP_WATCHDOG_TARGET_DIR)
	$(MAKE) -C $(APP_WATCHDOG_SRC_DIR) CC=$(TARGET_CC) CXX=$(TARGET_CXX) TARGET_DIR=$(APP_WATCHDOG_TARGET_DIR) TARGET_NAME=$(APP_WATCHDOG_TARGET_NAME)
	cp $(APP_WATCHDOG_TARGET_DIR)/$(APP_WATCHDOG_TARGET_NAME) $(TOP_DIR)/$(APP_WATCHDOG_TARGET_NAME)
test-clean:
	$(MAKE) -C $(APP_WATCHDOG_SRC_DIR) clean TARGET_DIR=$(APP_WATCHDOG_TARGET_DIR) TARGET_NAME=$(APP_WATCHDOG_TARGET_NAME)
	rm $(TOP_DIR)/$(APP_WATCHDOG_TARGET_NAME)

SRV   += test
SRV_CLEANS += test-clean
