TIMER_SRC_DIR	:= $(LIBS_DIR)/timer

TIMER_TARGET_DIR	:= $(TOP_DIR)/temp/libs/timer

TIMER_TARGET_NAME	:= orange_timer.$(LIB_SO_SUBFIX)

timer: 
	cd ${TIMER_SRC_DIR} && sh ./orange_timer_version.sh	
	$(MS_MAKEFILE_V)printf "$(COMPILE_P) $(TIMER_TARGET_NAME) $(NOCOLOR)\n"
	-$(MS_MAKEFILE_V)mkdir -p $(TIMER_TARGET_DIR)
	$(MS_MAKEFILE_V)$(MAKE) -C $(TIMER_SRC_DIR) CC=$(TARGET_CC) TARGET_DIR=$(TIMER_TARGET_DIR) TARGET_NAME=$(TIMER_TARGET_NAME)
	cp $(TIMER_TARGET_DIR)/$(TIMER_TARGET_NAME) $(PUBLIC_LIB_DIR)/$(TIMER_TARGET_NAME)
	rm ${TIMER_SRC_DIR}/orange_timer_version.c

timer-clean:
	$(MS_MAKEFILE_V)printf "$(CLEAN_P) $(TIMER_TARGET_NAME) $(NOCOLOR)\n"
	$(MS_MAKEFILE_V)$(MAKE) -C $(TIMER_SRC_DIR) clean TARGET_DIR=$(TIMER_TARGET_DIR) TARGET_NAME=$(TIMER_TARGET_NAME)
	-$(MS_MAKEFILE_V)rm -rf $(PUBLIC_LIB_DIR)/$(TIMER_TARGET_NAME)
	$(MS_MAKEFILE_V)printf  "$(COMPILE_SUCCESS_P) $(TIMER_TARGET_NAME) success $(NOCOLOR)\n"

LIBS   += timer
CLEANS += timer-clean


