SOCKET_SRC_DIR	:= $(LIBS_DIR)/socket

SOCKET_TARGET_DIR	:= $(TOP_DIR)/temp/libs/socket

SOCKET_TARGET_NAME	:= orange_socket.$(LIB_SO_SUBFIX)

socket: 
	cd ${SOCKET_SRC_DIR} && sh ./orange_socket_version.sh 
	$(MS_MAKEFILE_V)printf "$(COMPILE_P) $(SOCKET_TARGET_NAME) $(NOCOLOR)\n"
	-$(MS_MAKEFILE_V)mkdir -p $(SOCKET_TARGET_DIR)
	$(MS_MAKEFILE_V)$(MAKE) -C $(SOCKET_SRC_DIR) CC=$(TARGET_CC) TARGET_DIR=$(SOCKET_TARGET_DIR) TARGET_NAME=$(SOCKET_TARGET_NAME)
	cp $(SOCKET_TARGET_DIR)/$(SOCKET_TARGET_NAME) $(PUBLIC_LIB_DIR)/$(SOCKET_TARGET_NAME)
	rm ${SOCKET_SRC_DIR}/orange_socket_version.c

socket-clean:
	$(MS_MAKEFILE_V)printf "$(CLEAN_P) $(SOCKET_TARGET_NAME) $(NOCOLOR)\n"
	$(MS_MAKEFILE_V)$(MAKE) -C $(SOCKET_SRC_DIR) clean TARGET_DIR=$(SOCKET_TARGET_DIR) TARGET_NAME=$(SOCKET_TARGET_NAME)
	-$(MS_MAKEFILE_V)rm -rf $(PUBLIC_LIB_DIR)/$(SOCKET_TARGET_NAME)
	$(MS_MAKEFILE_V)printf  "$(COMPILE_SUCCESS_P) $(SOCKET_TARGET_NAME) success $(NOCOLOR)\n"

LIBS   += socket
CLEANS += socket-clean


