APP_WATCHDOG_SRC_DIR    := $(APPS_DIR)/watchdog/
APP_WATCHDOG_TARGET_DIR := $(TOP_DIR)/temp/app/watchdog
APP_WATCHDOG_TARGET_NAME:= watchdogd

xwatchdog:
	mkdir  -p $(APP_WATCHDOG_TARGET_DIR)
	$(MAKE) -C $(APP_WATCHDOG_SRC_DIR) CC=$(TARGET_CC) CXX=$(TARGET_CXX) TARGET_DIR=$(APP_WATCHDOG_TARGET_DIR) TARGET_NAME=$(APP_WATCHDOG_TARGET_NAME)
	cp $(APP_WATCHDOG_TARGET_DIR)/$(APP_WATCHDOG_TARGET_NAME) $(TOP_DIR)/$(APP_WATCHDOG_TARGET_NAME)
xwatchdog-clean:
	$(MAKE) -C $(APP_WATCHDOG_SRC_DIR) clean TARGET_DIR=$(APP_WATCHDOG_TARGET_DIR) TARGET_NAME=$(APP_WATCHDOG_TARGET_NAME)
	rm $(TOP_DIR)/$(APP_WATCHDOG_TARGET_NAME)

SRV   += xwatchdog
SRV_CLEANS += xwatchdog-clean
