MEVENT_SRC_DIR	:= $(LIBS_DIR)/mevent

MEVENT_TARGET_DIR	:= $(TOP_DIR)/temp/libs/mevent

MEVENT_TARGET_NAME	:= orange_mevent.$(LIB_SO_SUBFIX)

mevent: 
	cd ${MEVENT_SRC_DIR} && sh ./orange_mevent_version.sh	
	$(MS_MAKEFILE_V)printf "$(COMPILE_P) $(MEVENT_TARGET_NAME) $(NOCOLOR)\n"
	-$(MS_MAKEFILE_V)mkdir -p $(MEVENT_TARGET_DIR)
	$(MS_MAKEFILE_V)$(MAKE) -C $(MEVENT_SRC_DIR) CC=$(TARGET_CC) TARGET_DIR=$(MEVENT_TARGET_DIR) TARGET_NAME=$(MEVENT_TARGET_NAME)
	cp $(MEVENT_TARGET_DIR)/$(MEVENT_TARGET_NAME) $(PUBLIC_LIB_DIR)/$(MEVENT_TARGET_NAME)
	rm ${MEVENT_SRC_DIR}/orange_mevent_version.c

mevent-clean:
	$(MS_MAKEFILE_V)printf "$(CLEAN_P) $(MEVENT_TARGET_NAME) $(NOCOLOR)\n"
	$(MS_MAKEFILE_V)$(MAKE) -C $(MEVENT_SRC_DIR) clean TARGET_DIR=$(MEVENT_TARGET_DIR) TARGET_NAME=$(MEVENT_TARGET_NAME)
	-$(MS_MAKEFILE_V)rm -rf $(PUBLIC_LIB_DIR)/$(MEVENT_TARGET_NAME)
	$(MS_MAKEFILE_V)printf  "$(COMPILE_SUCCESS_P) $(MEVENT_TARGET_NAME) success $(NOCOLOR)\n"

LIBS   += mevent
CLEANS += mevent-clean


