EVENT_SRC_DIR	:= $(LIBS_DIR)/event

EVENT_TARGET_DIR	:= $(TOP_DIR)/temp/libs/event

EVENT_TARGET_NAME	:= orange_event.$(LIB_SO_SUBFIX)

event: 
	cd ${EVENT_SRC_DIR} && sh ./orange_event_version.sh	
	$(MS_MAKEFILE_V)printf "$(COMPILE_P) $(EVENT_TARGET_NAME) $(NOCOLOR)\n"
	-$(MS_MAKEFILE_V)mkdir -p $(EVENT_TARGET_DIR)
	$(MS_MAKEFILE_V)$(MAKE) -C $(EVENT_SRC_DIR) CC=$(TARGET_CC) TARGET_DIR=$(EVENT_TARGET_DIR) TARGET_NAME=$(EVENT_TARGET_NAME)
	cp $(EVENT_TARGET_DIR)/$(EVENT_TARGET_NAME) $(PUBLIC_LIB_DIR)/$(EVENT_TARGET_NAME)
	rm ${EVENT_SRC_DIR}/orange_event_version.c

event-clean:
	$(MS_MAKEFILE_V)printf "$(CLEAN_P) $(EVENT_TARGET_NAME) $(NOCOLOR)\n"
	$(MS_MAKEFILE_V)$(MAKE) -C $(EVENT_SRC_DIR) clean TARGET_DIR=$(EVENT_TARGET_DIR) TARGET_NAME=$(EVENT_TARGET_NAME)
	-$(MS_MAKEFILE_V)rm -rf $(PUBLIC_LIB_DIR)/$(EVENT_TARGET_NAME)
	-$(MS_MAKEFILE_V)rm $(EVENT_SRC_DIR)/orange_event_version.c
	$(MS_MAKEFILE_V)printf  "$(COMPILE_SUCCESS_P) $(EVENT_TARGET_NAME) success $(NOCOLOR)\n"

LIBS   += event
CLEANS += event-clean


